// Generated by xlinux. Do not edit.
//
// There's no ibtool on Linux, so Main.storyboard can't be compiled. This
// subclass of the project's SceneDelegate creates the window with the
// FlutterViewController in code, which is all Main.storyboard does.
import Flutter
import UIKit

class FlutterLinuxSceneDelegate: SceneDelegate {
  override func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    if window == nil, let windowScene = scene as? UIWindowScene {
      let window = UIWindow(windowScene: windowScene)
      window.rootViewController = FlutterViewController(project: nil, nibName: nil, bundle: nil)
      self.window = window
      window.makeKeyAndVisible()
    }
    super.scene(scene, willConnectTo: session, options: connectionOptions)
  }
}
