"""Flutter adapter: the equivalent of `flutter build ios` + Xcode.

`flutter assemble` (as Xcode calls it): App.framework + flutter_assets + native assets
          (release: Dart AOT with macOS's gen_snapshot running in Darling;
           debug: stub + kernel_blob.bin for the JIT)
then:     Runner (+ plugins via SwiftPM), Runner.app, .ipa
"""

import base64
import json
import plistlib
import re
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path

from ...core import app as appkit
from ...core import config, deps, extensions, toolchain
from ...core.util import DirLock, log, output, run
from . import plugins

ENGINE_BASE_URL = "https://storage.googleapis.com/flutter_infra_release/flutter"
SUPPORT = config.SUPPORT / "flutter"
# Replaces Main.storyboard (there's no ibtool on Linux).
SCENE_DELEGATE = "Runner.FlutterLinuxSceneDelegate"


class Project:
    def __init__(self, path, debug):
        self.dir = Path(path).resolve()
        if not (self.dir / "pubspec.yaml").exists():
            sys.exit(f"error: {self.dir} is not a Flutter project (no pubspec.yaml)")
        self.ios = self.dir / "ios"
        self.package = re.search(r"^name:\s*(\S+)", (self.dir / "pubspec.yaml").read_text(), re.M).group(1)
        self.debug = debug
        self.dart_defines = []
        self.pods_build = None  # CocoaPods plugins (plugins.build)
        self.build_dir = self.dir / ("build/ios-linux-debug" if debug else "build/ios-linux")
        self.app = self.build_dir / "Runner.app"
        self.ipa = self.build_dir / f"{self.package}.ipa"

    def bundle_identifier(self):
        return appkit.bundle_identifier(self.ios / "Runner.xcodeproj", exclude=("RunnerTests",))


def flutter_info():
    out = output(["flutter", "--version", "--machine"])
    info = json.loads(out[out.index("{"):])
    return Path(info["flutterRoot"]), info["engineRevision"]


def engine_dir(revision):
    return config.data_dir() / "flutter-engine" / revision


def ensure_engine(revision):
    """The engine's iOS artifacts (what `flutter precache --ios` would download)."""
    root = engine_dir(revision)
    for mode in ("ios", "ios-release"):
        target = root / mode
        if (target / "Flutter.xcframework").exists():
            continue
        log(f"Downloading {mode} engine artifacts ({revision[:10]})")
        target.mkdir(parents=True, exist_ok=True)
        archive = target / "artifacts.zip"
        urllib.request.urlretrieve(f"{ENGINE_BASE_URL}/{revision}/{mode}/artifacts.zip", archive)
        run(["unzip", "-qo", archive, "-d", target])
        archive.unlink()
    return root


GEN_SNAPSHOT_WRAPPER = """#!/usr/bin/env python3
# Generated by xlinux. The iOS gen_snapshot only exists for macOS:
# `flutter assemble` (release/profile) calls it and here it runs in Darling.
import sys
sys.path.insert(0, {repo!r})
from xlinux.core import darling
result = darling.run_macos_tool({real!r}, sys.argv[1:], capture_output=False, check=False)
sys.exit(result.returncode)
"""
MARKER = ".xlinux"
LEGACY_MARKER = ".flutter-ios-linux"  # the project's previous name


def link_engine_into_flutter_cache(flutter_root, engine):
    """`flutter assemble` looks for the iOS artifacts in its own cache (what
    `flutter precache --ios` would fill): they're linked to the ones in the
    data directory instead of being downloaded again. In ios-release,
    gen_snapshot_arm64 is replaced by a wrapper that runs it in Darling."""
    cache = flutter_root / "bin/cache/artifacts/engine"
    debug = cache / "ios"
    if not (debug.exists() and not debug.is_symlink()):  # a real precache is left alone
        if debug.is_symlink() and debug.resolve() != (engine / "ios").resolve():
            debug.unlink()
        if not debug.exists():
            debug.symlink_to(engine / "ios")

    release = cache / "ios-release"
    ours = any((release / m).exists() for m in (MARKER, LEGACY_MARKER))
    if release.exists() and not release.is_symlink() and not ours:
        return  # a real precache
    if release.is_symlink():
        release.unlink()
    release.mkdir(exist_ok=True)
    (release / MARKER).write_text(str(engine / "ios-release") + "\n")
    for item in (engine / "ios-release").iterdir():
        link = release / item.name
        if item.name == "gen_snapshot_arm64":
            continue
        if not link.is_symlink():
            link.symlink_to(item)
    wrapper = release / "gen_snapshot_arm64"
    if wrapper.is_symlink():
        wrapper.unlink()
    wrapper.write_text(GEN_SNAPSHOT_WRAPPER.format(
        repo=str(config.REPO), real=str(engine / "ios-release/gen_snapshot_arm64")))
    wrapper.chmod(0o755)


def assemble(project, frameworks):
    """`flutter assemble` the way Xcode calls it (xcode_backend.dart).

    Produces App.framework (debug: stub + kernel for the JIT; release: Dart AOT
    with gen_snapshot in Darling) + flutter_assets, and runs the native assets
    hooks, which need SdkRoot and `xcrun` (support/core/bin/xcrun)."""
    mode = "debug" if project.debug else "release"
    log(f"App.framework + flutter_assets + native assets (flutter assemble, {mode})")
    out = project.build_dir / "assemble"
    run(["flutter", "--no-version-check", "assemble", f"--output={out}/",
         "-dTargetPlatform=ios", "-dIosArchs=arm64", "-dTargetFile=lib/main.dart",
         f"-dBuildMode={mode}", f"-dConfiguration={mode.capitalize()}", f"-dSdkRoot={config.IPHONE_SDK}",
         f"-dTrackWidgetCreation={'true' if project.debug else 'false'}",
         f"-dTreeShakeIcons={'false' if project.debug else 'true'}", "-dDartObfuscation=false",
         "-dSplitDebugInfo=", "-dAction=build", f"-dSrcRoot={project.ios}",
         # Same encoding as flutter_tools: each KEY=VALUE in base64, comma-separated.
         "-dDartDefines=" + ",".join(base64.b64encode(d.encode()).decode() for d in project.dart_defines),
         f"{mode}_ios_bundle_flutter_assets"],
        cwd=project.dir, capture_output=True, text=True)
    shutil.copytree(out / "App.framework", frameworks / "App.framework", symlinks=True, dirs_exist_ok=True)
    # Native assets (Dart build hooks, e.g. objective_c via FFI): Xcode embeds them.
    for fw in (out / "native_assets").glob("*.framework"):
        shutil.copytree(fw, frameworks / fw.name, symlinks=True, dirs_exist_ok=True)


def compile_runner(project, flutter_fw_parent, obj, executable):
    """Runner without plugins: plain swiftc/clang (faster than SwiftPM)."""
    log("Native Runner (swiftc + iOS SDK)")
    obj.mkdir(parents=True, exist_ok=True)
    runner = project.ios / "Runner"
    objects = []
    for m in sorted(runner.glob("*.m")):
        o = obj / (m.stem + ".o")
        toolchain.clang(["-fobjc-arc", "-fmodules", "-O2", "-F", flutter_fw_parent, "-I", runner,
                         "-c", m, "-o", o])
        objects.append(o)
    args = ["-Onone" if project.debug else "-O", "-module-name", "Runner", "-F", flutter_fw_parent, "-I", runner]
    bridging = runner / "Runner-Bridging-Header.h"
    if bridging.exists():
        args += ["-import-objc-header", bridging]
    args += sorted(runner.glob("*.swift")) + [SUPPORT / "FlutterLinuxSceneDelegate.swift"] + objects
    args += [*toolchain.builtins(), "-framework", "Flutter", "-Xlinker", "-rpath", "-Xlinker", "@executable_path/Frameworks",
             "-o", executable]
    toolchain.swiftc(args)


def flutter_run_kernel(project_dir):
    """The debug kernel `flutter run` compiled right before calling the custom
    device's install command (for the linux bundle it builds and we ignore).
    It carries the run's --dart-define values, which our `flutter assemble`
    doesn't receive. The kernel is platform-neutral: the plugin registrant
    picks iOS at runtime, as with hot restart."""
    build_id = Path(project_dir) / "build/flutter_assets/.last_build_id"
    if not build_id.exists():
        return None
    kernel = Path(project_dir) / ".dart_tool/flutter_build" / build_id.read_text().strip() / "app.dill"
    return kernel if kernel.exists() else None


def read_dart_defines(defines=(), files=()):
    """--dart-define KEY=VALUE values plus --dart-define-from-file ones (a JSON
    object or a .env file), as flutter accepts them."""
    result = []
    for path in files:
        text = Path(path).read_text()
        if Path(path).suffix == ".json":
            values = json.loads(text)
        else:
            values = dict(line.split("=", 1) for line in text.splitlines()
                          if "=" in line and not line.lstrip().startswith("#"))
        result += [f"{k.strip()}={v.strip() if isinstance(v, str) else json.dumps(v)}" for k, v in values.items()]
    for define in defines:
        if "=" not in define:
            sys.exit(f"error: --dart-define expects KEY=VALUE, got {define!r}")
        result.append(define)
    return result


def build(project_dir, debug=False, package=True, kernel=None, dart_defines=()):
    """Build the app and return the Project with Runner.app (and the .ipa if
    `package`; installing on the iPhone only needs the uncompressed .app).
    `kernel`: debug kernel to ship instead of the one `flutter assemble` makes.
    `dart_defines`: KEY=VALUE strings, like `flutter build --dart-define`."""
    config.require_data_dir()
    toolchain.require_sdk()
    if not debug:
        deps.ensure_darling()  # gen_snapshot (Dart AOT) runs in Darling
    project = Project(project_dir, debug)
    project.dart_defines = list(dart_defines)
    # Held until the process exits: installing reads the .app we build here.
    project.lock = DirLock(project.build_dir, f"{project.package} ({'debug' if debug else 'release'})")
    flutter_root, revision = flutter_info()
    engine = ensure_engine(revision)
    link_engine_into_flutter_cache(flutter_root, engine)
    flutter_fw_parent = engine / ("ios" if debug else "ios-release") / "Flutter.xcframework/ios-arm64"

    if project.app.exists():
        shutil.rmtree(project.app)
    frameworks = project.app / "Frameworks"
    app_framework = frameworks / "App.framework"
    frameworks.mkdir(parents=True)

    run(["flutter", "pub", "get"], cwd=project.dir, stdout=subprocess.DEVNULL)
    assemble(project, frameworks)
    if debug and kernel:
        shutil.copyfile(kernel, app_framework / "flutter_assets/kernel_blob.bin")
    if plugins.swiftpm_plugins(project):
        out = plugins.build(project, flutter_fw_parent)
        toolchain.pack_swiftpm_outputs(out, project.app, "Runner", skip_frameworks=("Flutter",))
        plugins.pack_pod_resources(project, project.app)
        if project.pods_build:
            project.pods_build.assemble(project.app)
    else:
        compile_runner(project, flutter_fw_parent, project.build_dir / "obj", project.app / "Runner")

    log("Assembling Runner.app")
    with open(project.ios / "Flutter/AppFrameworkInfo.plist", "rb") as f:
        fw_info = plistlib.load(f)
    fw_info["MinimumOSVersion"] = config.MIN_IOS
    with open(app_framework / "Info.plist", "wb") as f:
        plistlib.dump(fw_info, f)
    shutil.copytree(flutter_fw_parent / "Flutter.framework", frameworks / "Flutter.framework",
                    ignore=shutil.ignore_patterns("_CodeSignature", "Headers", "Modules", "module.modulemap"))

    xc = appkit.read_xcconfig(project.ios / "Flutter/Generated.xcconfig")
    variables = {
        "EXECUTABLE_NAME": "Runner", "PRODUCT_NAME": "Runner", "PRODUCT_MODULE_NAME": "Runner",
        "DEVELOPMENT_LANGUAGE": "en",
        "PRODUCT_BUNDLE_IDENTIFIER": project.bundle_identifier(),
        "FLUTTER_BUILD_NAME": xc.get("FLUTTER_BUILD_NAME", "1.0.0"),
        "FLUTTER_BUILD_NUMBER": xc.get("FLUTTER_BUILD_NUMBER", "1"),
    }
    info = appkit.info_plist(project.ios / "Runner/Info.plist", variables, scene_delegate=SCENE_DELEGATE)
    if debug:
        # What `flutter build ios` adds in debug so the Dart VM service can be
        # advertised on the local network (otherwise: "Failed to register Dart
        # VM Service port with mDNS").
        services = info.setdefault("NSBonjourServices", [])
        if "_dartVmService._tcp" not in services:
            services.append("_dartVmService._tcp")
        info.setdefault("NSLocalNetworkUsageDescription",
                        "Allow Flutter tools on your computer to connect and debug your application. "
                        "This prompt will not appear on release builds.")
    appkit.add_icons(project.ios / "Runner/Assets.xcassets/AppIcon.appiconset", project.app, info)
    appkit.copy_loose_resources(project.ios / "Runner", project.app)
    appkit.write_info_plist(project.app, info)
    appkit.embed_entitlements(project.app / "Runner", appkit.entitlements_file(project.ios, "Runner/Info.plist"),
                              variables["PRODUCT_BUNDLE_IDENTIFIER"], variables)
    extensions.build_all(project.ios, project.app, project.build_dir, project.debug)
    toolchain.thin_frameworks(project.app)
    if package:
        appkit.package_ipa(project.app, project.ipa)
    log(f"Done: {project.ipa if package else project.app}")
    return project
