"""Flutter plugins that need real CocoaPods: podspec-only plugins with
Objective-C / C / C++ sources, which core/cocoapods (podspec -> SwiftPM)
doesn't convert.

On macOS Flutter adds them to ios/Podfile and `pod install` integrates the Pods
into Runner.xcodeproj. Here the Podfile lives in the data directory and
CocoaPods runs with `integrate_targets => false`, so the project is only read,
never modified. The pods are built with core/xcode (like React Native's) and
the Runner, built by SwiftPM, links them.
"""

import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

from ...core import config, deps, toolchain
from ...core.util import log
from ...core.xcode import build as xbuild
from ...core.xcode import package as xpackage
from ...core.xcode import project as xproject

TARGET = "Runner"
SOURCE_SUFFIXES = (".m", ".mm", ".c", ".cc", ".cpp")

# Flutter.framework comes from the engine through -F (as FRAMEWORK_SEARCH_PATHS
# does in Xcode): the pod only has to exist for plugins to depend on it, like
# the Flutter.podspec `flutter build ios` generates.
FLUTTER_PODSPEC = """Pod::Spec.new do |s|
  s.name = 'Flutter'
  s.version = '1.0.0'
  s.summary = 'A UI toolkit for beautiful and fast apps.'
  s.homepage = 'https://flutter.dev'
  s.license = { :type => 'BSD' }
  s.author = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
  s.source = { :git => 'https://github.com/flutter/engine.git', :tag => s.version.to_s }
  s.ios.deployment_target = '13.0'
  # Framework linking is handled by the tooling, not CocoaPods: a placeholder,
  # as in Flutter's own generated podspec.
  s.vendored_frameworks = 'path/to/nothing'
end
"""


def needs_cocoapods(package):
    """A podspec-only plugin with C-family sources."""
    if package.suffix != ".podspec":
        return False
    return any(f.suffix in SOURCE_SUFFIXES for f in package.parent.rglob("*") if f.is_file())


class PodsBuild:
    """Result of building the plugin pods: what the Runner needs to link them."""

    def __init__(self, project, pods, settings):
        self.project, self.pods, self.settings = project, pods, settings

    def framework_paths(self):
        return self.settings.list("FRAMEWORK_SEARCH_PATHS")

    def swiftpm_flags(self):
        """For `swift build`: headers for the registrant, libraries for the link."""
        flags = []
        for path in self.framework_paths():
            flags += ["-Xcc", f"-F{path}", "-Xswiftc", "-F", "-Xswiftc", path, "-Xlinker", "-F", "-Xlinker", path]
        for path in self.settings.list("LIBRARY_SEARCH_PATHS"):
            flags += ["-Xlinker", "-L", "-Xlinker", path]
        ld = self.settings.list("OTHER_LDFLAGS")
        i = 0
        while i < len(ld):
            if ld[i] in ("-framework", "-weak_framework") and i + 1 < len(ld):
                if ld[i + 1] != "Flutter":  # the Runner links the engine itself
                    flags += ["-Xlinker", ld[i], "-Xlinker", ld[i + 1]]
                i += 2
                continue
            flags += ["-Xlinker", ld[i]]
            i += 1
        return flags

    def assemble(self, app):
        """Dynamic frameworks and resource bundles the pods ship. Without target
        integration CocoaPods doesn't write Pods-Runner-frameworks.sh /
        -resources.sh, so they are taken from what was built."""
        intermediates = Path(self.settings.get("PODS_XCFRAMEWORKS_BUILD_DIR"))
        for fw in sorted(intermediates.glob("**/*.framework")) if intermediates.is_dir() else []:
            binary = fw / fw.stem
            if fw.name != "Flutter.framework" and toolchain._is_dynamic_library(binary.resolve()):
                shutil.copytree(fw.resolve(), app / "Frameworks" / fw.name, dirs_exist_ok=True,
                                ignore=lambda _, names: [n for n in names if n in xpackage.NOT_EMBEDDED])
        for bundle in xpackage.build_resource_bundles(self.pods):
            shutil.copytree(bundle, app / bundle.name, dirs_exist_ok=True)

def build(project, plugins, flutter_fw_parent):
    """pod install + build for `plugins` ([(name, basename, podspec)])."""
    key = hashlib.sha1(str(project.dir).encode()).hexdigest()[:8]
    work = config.data_dir() / "flutter-pods" / f"{project.package}-{key}"
    (work / "Flutter").mkdir(parents=True, exist_ok=True)
    (work / "Flutter/Flutter.podspec").write_text(FLUTTER_PODSPEC)
    pods = "\n".join(f"  pod '{name}', :path => '{podspec.parent}'" for name, _, podspec in plugins)
    podfile = f"""# Generated by xlinux. Do not edit.
platform :ios, '{config.MIN_IOS}'
install! 'cocoapods', :integrate_targets => false
use_frameworks! :linkage => :static
project '{project.ios / 'Runner.xcodeproj'}'

target '{TARGET}' do
  pod 'Flutter', :path => 'Flutter'
{pods}
end
"""
    if not (work / "Podfile").exists() or (work / "Podfile").read_text() != podfile \
            or not (work / "Pods/Manifest.lock").exists():
        (work / "Podfile").write_text(podfile)
        env = deps.ensure_cocoapods()
        log(f"pod install (CocoaPods plugins: {', '.join(n for n, _, _ in plugins)})")
        result = subprocess.run(["pod", "install"], cwd=work, env=env, capture_output=True, text=True)
        if result.returncode:
            sys.exit(f"error: pod install failed:\n{(result.stdout + result.stderr)[-4000:]}")

    configuration = "Debug" if project.debug else "Release"
    ruby = deps.ensure_cocoapods()
    pods = xproject.XcodeProject(xproject.dump(work / "Pods/Pods.xcodeproj", configuration, ruby),
                                 work / "build", configuration)
    context = xbuild.Context(work / "Pods", framework_paths=[flutter_fw_parent])
    try:
        built = xbuild.build_targets(pods, [f"Pods-{TARGET}"], context)
    except xbuild.BuildError as e:
        sys.exit(f"error: {e}")
    pods.prepare_all_xcframeworks()
    if built:
        log(f"CocoaPods plugins: {built} pod(s) rebuilt")
    return PodsBuild(project, pods, pods.settings(pods.targets[f"Pods-{TARGET}"]))
